# Generated by Django 5.0.6 on 2024-06-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=222)),
                ('cost', models.IntegerField()),
                ('count', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
